### ISSUE TITLE
Python projects have multiple manifests

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#1102]
Now that we have expanded our Python manifest support, many (or perhaps even most) Python projects have multiple lockfiles and manifest files, which results in odd behavior when using automatic lockfile detection.

For example, let's look at the [requests][1] project:

[1]: https://github.com/psf/requests

```
> rm requirements-dev.txt 

> phylum status
Project: null
Group: null
Project Root: null
Lockfiles:
 - path: ./docs/requirements.txt
   type: pip
 - path: ./pyproject.toml
   type: poetry
 - path: ./setup.py
   type: pip
 - path: ./setup.cfg
   type: pip
```

_Note: I first remove `requirements-dev.txt` because it gets picked up as a lockfile, which prevents the manifests from being included... This is a separate mistake and possibly deserves its own issue_

Phylum has picked up 3 separate manifests... `pyproject.toml`, `setup.py`, and `setup.cfg`. But because of some details, all three of these are effectively the same manifest.

<details>
<summary>Details for those that care</summary>

1. The `pyproject.toml` takes priority. But according to [PEP 517][]:
   > If the `pyproject.toml` file is absent, or the `build-backend` key is missing, the source tree is not using this specification, and tools should revert to the legacy behaviour of running `setup.py` (either directly, or by implicitly invoking the `setuptools.build_meta:__legacy__` backend).
2. The build system invokes `setup.py`, which calls the `setup()` function in [`setuptools`][setuptools].
3. `setuptools` [detects][] `setup.cfg` and uses these values to build the package

[PEP 517]: https://peps.python.org/pep-0517/
[setuptools]: https://setuptools.pypa.io/en/latest/index.html
[detects]: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html

</details>

**Comment by kylewillmon** [comment]
As far as I know, it's not possible to have a `setup.cfg` without also having a `setup.py`. So there is no reason for us to detect `setup.cfg` as a Python manifest. It is always sufficient to detect `setup.py` instead.

The interaction between `setup.py` and `pyproject.toml` is more complicated... There are Python projects with every combination of these two files, so we have to handle all cases.

**Comment by maxrake** [comment]
> As far as I know, it's not possible to have a `setup.cfg` without also having a `setup.py`. So there is no reason for us to detect `setup.cfg` as a Python manifest. It is always sufficient to detect `setup.py` instead.

Here is the relevant reference on [`setup.cfg`-only projects](https://setuptools.pypa.io/en/latest/setuptools.html#setup-cfg-only-projects
)

Here is an example of a package that has a minimal `setup.py`, a full `setup.cfg` and NO `pyproject.toml`:

<details><summary>Details</summary>
<p>

```
~/Downloads/pronto-2.5.4  2  7 via 🐍 v3.11.3
❯ pip-compile --version
pip-compile, version 6.13.0

~/Downloads/pronto-2.5.4  2  7 via 🐍 v3.11.3
❯ l
total 112
drwxr-xr-x@ 11 maxrake  staff   352B May 18 14:31 .
drwx------+ 38 maxrake  staff   1.2K May  8 20:47 ..
-rw-r--r--@  1 maxrake  staff    17K Apr 10 12:49 CHANGELOG.md
-rw-r--r--@  1 maxrake  staff   1.1K Apr 10 12:49 COPYING
-rw-r--r--@  1 maxrake  staff   134B Apr 10 12:49 MANIFEST.in
-rw-r--r--@  1 maxrake  staff   9.2K Apr 10 12:49 PKG-INFO
-rw-r--r--@  1 maxrake  staff   7.7K Apr 10 12:49 README.md
drwxr-xr-x@ 17 maxrake  staff   544B Apr 10 12:49 pronto
drwxr-xr-x@  8 maxrake  staff   256B Apr 10 12:49 pronto.egg-info
-rw-r--r--@  1 maxrake  staff   2.6K May 12 15:44 setup.cfg
-rw-r--r--@  1 maxrake  staff    60B Apr 10 12:49 setup.py

~/Downloads/pronto-2.5.4  2  7 via 🐍 v3.11.3
❯ cat setup.py
#!/usr/bin/env python

import setuptools
setuptools.setup()

~/Downloads/pronto-2.5.4  2  7 via 🐍 v3.11.3
❯ cat setup.cfg
[metadata]
name = pronto
version = attr: pronto.__version__
author = Martin Larralde
author-email = martin.larralde@embl.de
home-page = https://github.com/althonos/pronto
description = Python frontend to ontologies.
long-description = file: README.md
long_description_content_type = text/markdown
license = MIT
license-file = COPYING
platform = any
keywords = bioinformatics, ontology, OBO, OWL, convert, parse
classifiers =
	Development Status :: 4 - Beta
	Programming Language :: Python
	Programming Language :: Python :: 3
	Programming Language :: Python :: 3.7
	Programming Language :: Python :: 3.8
	Programming Language :: Python :: 3.9
	Programming Language :: Python :: 3.10
	Programming Language :: Python :: 3.11
	Intended Audience :: Developers
	Intended Audience :: Science/Research
	Intended Audience :: Healthcare Industry
	License :: OSI Approved :: MIT License
	Topic :: Scientific/Engineering :: Bio-Informatics
	Topic :: Software Development :: Libraries :: Python Modules
	Operating System :: OS Independent
	Typing :: Typed
project_urls =
	Bug Tracker = https://github.com/althonos/pronto/issues
	Changelog = https://pronto.readthedocs.io/en/latest/changes.html
	Documentation = https://pronto.readthedocs.io/en/latest/
	Coverage = https://app.codecov.io/gh/althonos/pronto
	CI = https://github.com/althonos/pronto/actions

[options]
zip_safe = true
include_package_data = true
python_requires = >= 3.7
packages =
	pronto
	pronto.entity
	pronto.logic
	pronto.utils
	pronto.parsers
	pronto.serializers
test_suite = tests
setup_requires =
	setuptools >=46.4
install_requires =
	chardet ~=5.0
	fastobo ~=0.12.2
	networkx >=2.3,<4.0
	python-dateutil ~=2.8

[options.package_data]
pronto = py.typed

[sdist]
formats = zip

[bdist_wheel]
universal = 1

[coverage:report]
exclude_lines =
	pragma: no cover
	raise NotImplementedError
	if __name__ == .__main__.:
	except ImportError:
	if typing.TYPE_CHECKING:
	@abc.abstractmethod

[coverage:run]
branch = True
source = pronto

[green]
file-pattern = test_*.py
verbose = 2
no-skip-report = true
quiet-stdout = true
run-coverage = true

[pydocstyle]
inherit = false
ignore = D100,D101,D102,D105,D107,D200,D203,D213,D406,D407
match-dir = (?!tests)(?!resources)(?!docs)(?!build)[^\.].*
match = (?!test)(?!setup)[^\._].*\.py

[mypy]
ignore_missing_imports = true

[mypy-pronto.*]
disallow_any_decorated = false
disallow_any_generics = false
disallow_any_unimported = false
disallow_subclassing_any = true
disallow_untyped_calls = false
disallow_untyped_defs = false
ignore_missing_imports = false
warn_unused_ignores = false
warn_return_any = false

[egg_info]
tag_build =
tag_date = 0


~/Downloads/pronto-2.5.4  2  7 via 🐍 v3.11.3
❯ pip-compile -o requirements-locked.txt -v setup.py
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
Getting build dependencies for wheel...
Installing packages in isolated environment... (setuptools >=46.4, wheel)
Getting metadata for wheel...
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  chardet~=5.0 (from pronto (setup.py))
  fastobo~=0.12.2 (from pronto (setup.py))
  networkx<4.0,>=2.3 (from pronto (setup.py))
  python-dateutil~=2.8 (from pronto (setup.py))

Finding the best candidates:
  found candidate chardet==5.1.0 (constraint was ~=5.0)
  found candidate fastobo==0.12.2 (constraint was ~=0.12.2)
  found candidate networkx==3.1 (constraint was >=2.3,<4.0)
  found candidate python-dateutil==2.8.2 (constraint was ~=2.8)

Finding secondary dependencies:
  chardet==5.1.0            requires -
  networkx==3.1             requires -
  fastobo==0.12.2           requires -
  python-dateutil==2.8.2    requires six>=1.5

New dependencies found in this round:
  adding ('six', '>=1.5', [])
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  chardet~=5.0 (from pronto (setup.py))
  fastobo~=0.12.2 (from pronto (setup.py))
  networkx<4.0,>=2.3 (from pronto (setup.py))
  python-dateutil~=2.8 (from pronto (setup.py))
  six>=1.5 (from python-dateutil==2.8.2->pronto (setup.py))

Finding the best candidates:
  found candidate chardet==5.1.0 (constraint was ~=5.0)
  found candidate fastobo==0.12.2 (constraint was ~=0.12.2)
  found candidate networkx==3.1 (constraint was >=2.3,<4.0)
  found candidate python-dateutil==2.8.2 (constraint was ~=2.8)
  found candidate six==1.16.0 (constraint was >=1.5)

Finding secondary dependencies:
  fastobo==0.12.2           requires -
  six==1.16.0               requires -
  networkx==3.1             requires -
  chardet==5.1.0            requires -
  python-dateutil==2.8.2    requires six>=1.5
------------------------------------------------------------
Result of round 2: stable, done

#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --output-file=requirements-locked.txt setup.py
#
chardet==5.1.0
    # via pronto (setup.py)
fastobo==0.12.2
    # via pronto (setup.py)
networkx==3.1
    # via pronto (setup.py)
python-dateutil==2.8.2
    # via pronto (setup.py)
six==1.16.0
    # via python-dateutil

~/Downloads/pronto-2.5.4  2  8 via 🐍 v3.11.3 took 4s
❯ cat requirements-locked.txt
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --output-file=requirements-locked.txt setup.py
#
chardet==5.1.0
    # via pronto (setup.py)
fastobo==0.12.2
    # via pronto (setup.py)
networkx==3.1
    # via pronto (setup.py)
python-dateutil==2.8.2
    # via pronto (setup.py)
six==1.16.0
    # via python-dateutil

~/Downloads/pronto-2.5.4  2  8 via 🐍 v3.11.3
❯ mv setup.py setup.bak

~/Downloads/pronto-2.5.4  2  8
❯ pip-compile -o requirements-locked-cfg-only.txt -v setup.cfg
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Traceback (most recent call last):
  File "/Users/maxrake/.local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/piptools/scripts/compile.py", line 496, in cli
    metadata = project_wheel_metadata(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/build/util.py", line 43, in project_wheel_metadata
    builder = build.ProjectBuilder(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/build/__init__.py", line 267, in __init__
    _validate_source_directory(srcdir)
  File "/Users/maxrake/.local/pipx/venvs/pip-tools/lib/python3.11/site-packages/build/__init__.py", line 135, in _validate_source_directory
    raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
build.BuildException: Source /Users/maxrake/Downloads/pronto-2.5.4 does not appear to be a Python project: no pyproject.toml or setup.py

~/Downloads/pronto-2.5.4  2  8
❌ 1 ❯ mv setup.bak setup.py

~/Downloads/pronto-2.5.4  2  8 via 🐍 v3.11.3
❯ pip-compile -o requirements-locked-cfg.txt -v setup.cfg
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
Getting build dependencies for wheel...
Installing packages in isolated environment... (setuptools >=46.4, wheel)
Getting metadata for wheel...
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  chardet~=5.0 (from pronto (setup.cfg))
  fastobo~=0.12.2 (from pronto (setup.cfg))
  networkx<4.0,>=2.3 (from pronto (setup.cfg))
  python-dateutil~=2.8 (from pronto (setup.cfg))

Finding the best candidates:
  found candidate chardet==5.1.0 (constraint was ~=5.0)
  found candidate fastobo==0.12.2 (constraint was ~=0.12.2)
  found candidate networkx==3.1 (constraint was >=2.3,<4.0)
  found candidate python-dateutil==2.8.2 (constraint was ~=2.8)

Finding secondary dependencies:
  python-dateutil==2.8.2    requires six>=1.5
  chardet==5.1.0            requires -
  fastobo==0.12.2           requires -
  networkx==3.1             requires -

New dependencies found in this round:
  adding ('six', '>=1.5', [])
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  chardet~=5.0 (from pronto (setup.cfg))
  fastobo~=0.12.2 (from pronto (setup.cfg))
  networkx<4.0,>=2.3 (from pronto (setup.cfg))
  python-dateutil~=2.8 (from pronto (setup.cfg))
  six>=1.5 (from python-dateutil==2.8.2->pronto (setup.cfg))

Finding the best candidates:
  found candidate chardet==5.1.0 (constraint was ~=5.0)
  found candidate fastobo==0.12.2 (constraint was ~=0.12.2)
  found candidate networkx==3.1 (constraint was >=2.3,<4.0)
  found candidate python-dateutil==2.8.2 (constraint was ~=2.8)
  found candidate six==1.16.0 (constraint was >=1.5)

Finding secondary dependencies:
  six==1.16.0               requires -
  fastobo==0.12.2           requires -
  python-dateutil==2.8.2    requires six>=1.5
  chardet==5.1.0            requires -
  networkx==3.1             requires -
------------------------------------------------------------
Result of round 2: stable, done

#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --output-file=requirements-locked-cfg.txt setup.cfg
#
chardet==5.1.0
    # via pronto (setup.cfg)
fastobo==0.12.2
    # via pronto (setup.cfg)
networkx==3.1
    # via pronto (setup.cfg)
python-dateutil==2.8.2
    # via pronto (setup.cfg)
six==1.16.0
    # via python-dateutil

~/Downloads/pronto-2.5.4  2  9 via 🐍 v3.11.3 took 4s
❯ diff requirements-locked.txt requirements-locked-cfg.txt
5c5
< #    pip-compile --output-file=requirements-locked.txt setup.py
---
> #    pip-compile --output-file=requirements-locked-cfg.txt setup.cfg
8c8
<     # via pronto (setup.py)
---
>     # via pronto (setup.cfg)
10c10
<     # via pronto (setup.py)
---
>     # via pronto (setup.cfg)
12c12
<     # via pronto (setup.py)
---
>     # via pronto (setup.cfg)
14c14
<     # via pronto (setup.py)
---
>     # via pronto (setup.cfg)
```

</p>
</details> 

That is a lot of output, but the interesting part is this error:

```
build.BuildException: Source /Users/maxrake/Downloads/pronto-2.5.4 does not appear to be a Python project: no pyproject.toml or setup.py
```

So, it appears `pip-compile` is using `build` as the "compatible build frontend" but without the requisite entries in `pyproject.toml`, `setup.cfg`-only projects will fail.

**Comment by cd-work** [comment]
This issue doesn't really sound actionable to me at the moment.

To my knowledge we do detect these manifests and we can correctly generate their lockfiles. So which changes are required to "solve" this issue?

Is the target to remove part of these lockfiles when another is present that (should) have priority? It doesn't sound like we have a reliably way of detecting this.

**Comment by kylewillmon** [comment]
Now that `setup.cfg` has been removed, the only thing left here is to favor `pyproject.toml` over `setup.py` when both are present.
