### ISSUE TITLE
`phylum pip install --help` fails

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#989]
Getting help output from the `install` subcommand results in an error:

```console
../cli  15  19 on  pip [?] via 🦕 via 🐍 v3.11.2 (pip_ext_test) via 🦀 v1.68.0
❯ target/debug/phylum pip install -h
[phylum] Finding new dependencies…
Extension error: Uncaught SyntaxError: Unexpected token 'U', "
Usage:
"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseDryRun (file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:184:25)
    at checkDryRun (file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:159:22)
    at file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:44:7

../cli  15  19 on  pip [?] via 🦕 via 🐍 v3.11.2 (pip_ext_test) via 🦀 v1.68.0
❯ target/debug/phylum pip install --help
[phylum] Finding new dependencies…
Extension error: Uncaught SyntaxError: Unexpected token 'U', "
Usage:
"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseDryRun (file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:184:25)
    at checkDryRun (file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:159:22)
    at file:///Users/maxrake/.local/share/phylum/extensions/pip/main.ts:44:7

../cli  15  19 on  pip [?] via 🦕 via 🐍 v3.11.2 (pip_ext_test) via 🦀 v1.68.0
❯ target/debug/phylum pip --help
[phylum] This extension does not support arguments before the first subcommand. Please open an issue if "--help" is not an argument.

../cli  15  19 on  pip [?] via 🦕 via 🐍 v3.11.2 (pip_ext_test) via 🦀 v1.68.0
❌ 125 ❯ target/debug/phylum pip list -h

Usage:
  pip3 list [options]

Description:
  List installed packages, including editables.

  Packages are listed in a case-insensitive sorted order.
---TRIMMED---
```

_Originally posted by @maxrake in https://github.com/phylum-dev/cli/pull/980#discussion_r1148000467_

**Comment by cd-work** [comment]
I'd assume this to be the case for more than just our `pip` extension tbh.

**Comment by maxrake** [comment]
> I'd assume this to be the case for more than just our `pip` extension tbh.

The current official `poetry` extension correctly handles `--help` output:

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/18729796/228372815-fb420976-3d4f-400d-99c9-c0bb5aa13607.png">

<details><summary>`npm` kind of works (click to expand)</summary>
<p>

```console
../phylum-ui  6  19 on  develop [?] via  v19.8.1
❯ phylum npm install -h
[phylum] Updating lockfile…
Install a package

Usage:
npm install [<package-spec> ...]

Options:
[-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
[-E|--save-exact] [-g|--global]
[--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
[--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
[--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
[--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
[-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
[-ws|--workspaces] [--include-workspace-root] [--install-links]

aliases: add, i, in, ins, inst, insta, instal, isnt, isnta, isntal, isntall

Run "npm help install" for more info
[phylum] Lockfile updated successfully.

[phylum] Analyzing packages…
[phylum] All packages pass project thresholds.

[phylum] Installing without build scripts…
Install a package

Usage:
npm install [<package-spec> ...]

Options:
[-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
[-E|--save-exact] [-g|--global]
[--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
[--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
[--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
[--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
[-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
[-ws|--workspaces] [--include-workspace-root] [--install-links]

aliases: add, i, in, ins, inst, insta, instal, isnt, isnta, isntal, isntall

Run "npm help install" for more info
[phylum] Packages installed successfully.

[phylum] Running build scripts inside sandbox…
[..................] | idealTree:phylum-ui: sill idealTree buildDeps
---STALLS-HERE---

../phylum-ui  6  19 on  develop [?] via  v19.8.1
❯ phylum npm help install

../phylum-ui  6  19 on  develop [?] via  v19.8.1 took 2s
❯ (it worked as expected)

```

</p>
</details>

<details><summary>`yarn` kind of worked (click to expand)</summary>
<p>

The help output is printed (as desired), but then the extension continues on to "Building packages inside sandbox…" which is a bit unexpected.

```console
../phylum-ui  6  18 on  develop via  v19.8.1
❯ phylum yarn add -h
[phylum] Updating lockfile…
warning Skipping preferred cache folder "/Users/maxrake/Library/Caches/Yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-501".

  Usage: yarn add [packages ...] [flags]

  Installs a package and any packages that it depends on.

  Options:

    -v, --version                       output the version number
    --no-default-rc                     prevent Yarn from automatically detecting yarnrc and npmrc files
    --use-yarnrc <path>                 specifies a yarnrc file that Yarn should use (.yarnrc only, not .npmrc) (default: )
    --verbose                           output verbose messages on internal operations
    --offline                           trigger an error if any required dependencies are not available in local cache
    --prefer-offline                    use network only if dependencies are not available in local cache
    --enable-pnp, --pnp                 enable the Plug'n'Play installation
    --disable-pnp                       disable the Plug'n'Play installation
    --strict-semver
    --json                              format Yarn log messages as lines of JSON (see jsonlines.org)
    --ignore-scripts                    don't run lifecycle scripts
    --har                               save HAR output of network traffic
    --ignore-platform                   ignore platform checks
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --force                             install and build packages even if they were built before, overwrite lockfile
    --skip-integrity-check              run install without checking if node_modules is installed
    --check-files                       install will verify file tree of packages for consistency
    --no-bin-links                      don't generate bin links when setting up packages
    --flat                              only allow one version of a package
    --prod, --production [prod]
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --update-checksums                  update package checksums from current repository
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --global-folder <path>              specify a custom folder to store global packages
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --emoji [bool]                      enable emoji in output (default: true)
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --cwd <cwd>                         working directory to use (default: /Users/maxrake/dev/phylum/localdev/phylum-ui)
    --proxy <host>
    --https-proxy <host>
    --registry <url>                    override configuration registry
    --no-progress                       disable progress bar
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --non-interactive                   do not show interactive prompts
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --no-node-version-check             do not warn when using a potentially unsupported Node version
    --focus                             Focus on a single workspace by installing remote copies of its sibling workspaces.
    --otp <otpcode>                     one-time password for two factor authentication
    -W, --ignore-workspace-root-check   required to run yarn add inside a workspace root
    -D, --dev                           save package to your `devDependencies`
    -P, --peer                          save package to your `peerDependencies`
    -O, --optional                      save package to your `optionalDependencies`
    -E, --exact                         install exact version
    -T, --tilde                         install most recent release with the same minor version
    -A, --audit                         Run vulnerability audit on installed packages
    -h, --help                          output usage information
  Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

[phylum] Lockfile updated successfully.

[phylum] Analyzing packages…
[phylum] All packages pass project thresholds.

[phylum] Downloading packages to cache…

  Usage: yarn add [packages ...] [flags]

  Installs a package and any packages that it depends on.

  Options:

    -v, --version                       output the version number
    --no-default-rc                     prevent Yarn from automatically detecting yarnrc and npmrc files
    --use-yarnrc <path>                 specifies a yarnrc file that Yarn should use (.yarnrc only, not .npmrc) (default: )
    --verbose                           output verbose messages on internal operations
    --offline                           trigger an error if any required dependencies are not available in local cache
    --prefer-offline                    use network only if dependencies are not available in local cache
    --enable-pnp, --pnp                 enable the Plug'n'Play installation
    --disable-pnp                       disable the Plug'n'Play installation
    --strict-semver
    --json                              format Yarn log messages as lines of JSON (see jsonlines.org)
    --ignore-scripts                    don't run lifecycle scripts
    --har                               save HAR output of network traffic
    --ignore-platform                   ignore platform checks
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --force                             install and build packages even if they were built before, overwrite lockfile
    --skip-integrity-check              run install without checking if node_modules is installed
    --check-files                       install will verify file tree of packages for consistency
    --no-bin-links                      don't generate bin links when setting up packages
    --flat                              only allow one version of a package
    --prod, --production [prod]
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --update-checksums                  update package checksums from current repository
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --global-folder <path>              specify a custom folder to store global packages
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --emoji [bool]                      enable emoji in output (default: true)
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --cwd <cwd>                         working directory to use (default: /Users/maxrake/dev/phylum/localdev/phylum-ui)
    --proxy <host>
    --https-proxy <host>
    --registry <url>                    override configuration registry
    --no-progress                       disable progress bar
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --non-interactive                   do not show interactive prompts
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --no-node-version-check             do not warn when using a potentially unsupported Node version
    --focus                             Focus on a single workspace by installing remote copies of its sibling workspaces.
    --otp <otpcode>                     one-time password for two factor authentication
    -W, --ignore-workspace-root-check   required to run yarn add inside a workspace root
    -D, --dev                           save package to your `devDependencies`
    -P, --peer                          save package to your `peerDependencies`
    -O, --optional                      save package to your `optionalDependencies`
    -E, --exact                         install exact version
    -T, --tilde                         install most recent release with the same minor version
    -A, --audit                         Run vulnerability audit on installed packages
    -h, --help                          output usage information
  Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

[phylum] Cache updated successfully.

[phylum] Building packages inside sandbox…
yarn install v1.22.19
warning Skipping preferred cache folder "/Users/maxrake/Library/Caches/Yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-501".
info There appears to be trouble with your network connection. Retrying...
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "is-typed-array@1.1.9" is incompatible with requested version "is-typed-array@^1.1.10"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.1"
warning Resolution field "nth-check@2.0.1" is incompatible with requested version "nth-check@^1.0.2"
[3/5] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Could not write file "/Users/maxrake/dev/phylum/localdev/phylum-ui/yarn-error.log": "EPERM: operation not permitted, open '/Users/maxrake/dev/phylum/localdev/phylum-ui/yarn-error.log'"
error An unexpected error occurred: "https://registry.yarnpkg.com/nth-check/-/nth-check-2.0.1.tgz: getaddrinfo ENOTFOUND registry.yarnpkg.com".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[phylum] Sandboxed build failed.
[phylum]
[phylum] This could mean one of your packages attempted to access a restricted resource.
[phylum] Do not retry installation without Phylum's extension.
[phylum]
[phylum] Please submit your lockfile to Phylum should this error persist.

../phylum-ui  6  18 on  develop via  v19.8.1 took 29s
❌ 1 ❯
```

</p>
</details> 

Getting this feature to work is necessary if the documentation is suggesting users to alias these default extensions (e.g., `alias npm='phylum npm'`) because a very natural way to use these tools is to ask for the help output _before_ running a particular command.
